# Generated by Django 4.0.6 on 2022-07-23 15:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='link',
            new_name='project_link',
        ),
        migrations.AddField(
            model_name='project',
            name='short_description',
            field=models.TextField(default='lorem ipsum dolor sit amet, consectetur adipiscing'),
        ),
        migrations.AddField(
            model_name='project',
            name='short_title',
            field=models.CharField(default='loremp', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='where_is_projects_on_website',
            field=models.URLField(default='lol'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
