# Generated by Django 4.0.6 on 2022-07-23 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_link_project_project_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=models.CharField(default='lorem ipsum dolor sit amet, consectetur adipiscing', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='where_is_projects_on_website',
            field=models.CharField(max_length=100),
        ),
    ]
