# Generated by Django 4.0.6 on 2022-07-25 19:41

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_project_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('priority', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CVItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor_uploader.fields.RichTextUploadingField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True)),
                ('category', models.ForeignKey(default='Uncategorized', on_delete=django.db.models.deletion.SET_DEFAULT, to='main.cvcategory', to_field='name')),
            ],
        ),
    ]
