# Generated by Django 4.0.6 on 2022-07-26 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_cvitem_end_date_remove_cvitem_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvitem',
            name='level',
            field=models.CharField(choices=[('UNDERGRADUATE', 'undergraduate'), ('HIGH SCHOOL', 'high school')], default='HIGH SCHOOL', max_length=100),
        ),
    ]
