# Generated by Django 4.0.6 on 2022-07-26 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_cvitem_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cvitem',
            name='level',
        ),
    ]
