# Generated by Django 4.0.6 on 2022-07-27 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_cvitem_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVItemListExpandible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('expand', models.JSONField()),
                ('category', models.ForeignKey(default='Uncategorized', on_delete=django.db.models.deletion.SET_DEFAULT, to='main.cvcategory', to_field='name')),
            ],
        ),
    ]
