# Generated by Django 4.0.6 on 2022-07-29 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_contactitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactitem',
            name='first_name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
